using System;
using System.Collections.Generic;

namespace Alunite
{
    /// <summary>
    /// Contains cached data and settings for rendering.
    /// </summary>
    public class Visual
    {
        /// <summary>
        /// Gets a signal of views that shows what is seen by an untransformed camera in an environment.
        /// </summary>
        public static Signal<View> GetViewFeed(Span Environment)
        {
            return new ViewSignal(Environment);
        }
    }

    /// <summary>
    /// A signal of views generated by cameras.
    /// </summary>
    public class ViewSignal : Signal<View>
    {
        public ViewSignal(Span Environment)
        {
            this._Environment = Environment;
        }

        public override View this[double Time]
        {
            get
            {
                return new View(this._Environment[Time]);
            }
        }

        public override Signal<View> Simplify
        {
            get
            {
                this._Environment = this._Environment.Simplify;
                return this;
            }
        }

        private Span _Environment;
    }

    /// <summary>
    /// A view of a simulation that can be rendered to a graphics context.
    /// </summary>
    public class View
    {
        public View(Entity Entity)
        {
            this._Entity = Entity;
        }

        /// <summary>
        /// Gets the single entity that represents what is seen. The view is looking at the entity from (0.0, 0.0, 0.0) towards (1.0, 0.0, 0.0) with
        /// (0.0, 0.0, 1.0) as the up vector.
        /// </summary>
        public Entity Entity
        {
            get
            {
                return this._Entity;
            }
        }

        private Entity _Entity;
    }
}